### PR TITLE
Added ConsentStringBuilder.

### PR DESCRIPTION
**Pull request by vstefanyuk**
Implemented ConsentStringBuilder and appropriate test.

Moved constants used by ConsentStringParser to ConstentStringConstants-interface to make those re-usable by ConsentStringBuilder.

Note: at the moment only BitField encoding is implemented, Range encoding will follow.

### CODE REVIEW

**Comment by vstefanyuk** [comment]
Yes, exactly.

And thought as you told it is not directly needed for business like us
(DataXu), we do need ConsentStringBuilder for testing purposes. To test
properly our functionality which does work with ConsentStringParser we have
to have possibility to create those strings with test data. And we think it
would be useful for other companies like our.

**Comment by chrispaterson** [comment]
@vstefanyuk would you mind moving it into a gdpr.utils or gdpr.tools directory or something, to denote that it's a utility and doesn't need to be included in production build?  Then I think this could be useful.  Also, there is potentially a use case for this in in-app contexts, but I'm thinking about breaking out a separate android java consent string sdk.

**Comment by vstefanyuk** [comment]
@chrispaterson done

And, next week or bit later we are going to improve Builder by adding support for Range encoding and automatic choosing the most optimal encoding type.

It will be done as separate PR, so if you are ready to merge current PR to the master - go on :)

Thanks!

**Comment by chrispaterson** [comment]
Fixed by #20

**Pull request closed without merging**
