### PR TITLE
Builder methods to create vendor consent string

### PR DESCRIPTION
**Pull request by anupash**
Minor refactoring. Separated the consent parsing login into its own class.
Also, added the builder methods for vendor consent. builder supports both creation with bit field and range entry. 

Currently, vendor consent string created with builder omits base64 padding in accordance with the method framework specifications.

### CODE REVIEW

**Comment by vstefanyuk** [comment]
https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/pull/18 :)

**Comment by Kevin-P-Kerr** [comment]
I think this looks good.  @vstefanyuk  since this also implements range encoding I think we can just take this and spare you guys the work of double implementing.

**Comment by vstefanyuk** [comment]
I do think this PR was accepted too early. Here are just a few points:

1. maxVendorId is important thing. It should not be set manually. And in this case it settle explicitly in the builder. It has to be calculate value based on vendors added to the builder.
2. use BitField or RangeField mode has to be detected automatically to find the most efficient way to present consentString, setting it manually is useless.

We didn't implement Range mode yet exactly because if this reason - without automatic detection it is useless.

**Comment by chrispaterson** [comment]
My apologies @vstefanyuk would you mind submitting another PR?  I don't think I can reopen this one.

**Comment by vstefanyuk** [comment]
@chrispaterson I could. But if it will be created against current master it would be hardly observable. Do it anyway?

**Comment by nabcos** [comment]
> We didn't implement Range mode yet exactly because if this reason - without automatic detection it is useless.

It's just a builder though, and should contain minimal logic. IMO automation should be built in the application around it (or library in this case, additional tooling method comes to mind which detects exactly that, so that the builder can be set up appropriately).

**Pull request merged**
