### PR TITLE
[Feature] Init build.gradle productization

### PR DESCRIPTION
**Pull request by turu**
The purpose of this PR is to start applying some necessary productization to the build config, so that this library can be safely and easily used in external projects soon. Changes:
* configure project name in settings.gradle to adhere to Maven artifact naming conventions (see https://maven.apache.org/guides/mini/guide-naming-conventions.html)
* set groupId to com.iab.gdpr
* init versioning scheme, by setting version to 1.0.0-SNAPSHOT
* set source/target compatibility to Java 8. Important point to discuss: is supporting Java versions older than 1.8 required? 
* refactor dependencies formatting
* add tiny entry to the README file, describing how to start using the library

Also, once the library starts being published to a public Maven repository (see the critical issue #6), some versioning and branching strategies should be established, documented and enforced. This is discussed in #7.

### CODE REVIEW

**Comment by Jivyx** [comment]
Hi,

A point about Java 8 support, Android does not support all Java 8 features (java.time.Instant used in this library is for exemple not available for all versions of Android, only for Android O).

Do we consider this library for Android dev or not ? If yes, targeting Java 7 should be considered.

**Comment by OlegIakovlev** [comment]
Just a thought on java 7 backward compatibility - such things might be the most pain in library development especially taking into account http://www.oracle.com/technetwork/java/eol-135779.html as this means that to be java 7 compatible you need to build on java 7, so you need to run it on the unsupported version 🙂 but yeah, there is no easy way for Android devs to ommit this...

**Comment by Kevin-P-Kerr** [comment]
hey @turu @OlegIakovlev  @Jivyx 

just fyi that you can get this project through maven/gradle here https://search.maven.org/#artifactdetails%7Ccom.triplelift.gdpr%7Cconsent-string-parser%7C1.1.0%7Cjar

The current source is from https://github.com/triplelift/IAB-Consent-String-Parser

There are no differences between our fork and this repo.  It's just that I needed a repo with write access to publish this through sonatype.

**Comment by Jivyx** [comment]
Hi,

@chrispaterson Can we have a decision about Java 7 (and Android) support please ?

**Comment by chrispaterson** [comment]
I'm thinking that perhaps we need to break the Java lib into a server-side version an an android version.  I think there are some who are looking at writing a CMP as a native android app and could use the ability to generate consent strings as well as read them.  Also since Android has some API differences etc, to keep the server-side code lightweight and uncluttered we should probably split the two.

As far as back-porting the version to 7 I see a need for that.  Would there be a way to maintain both versions within this repo?

**Comment by lanusau** [comment]
Changes from this were included in #30 . Closing this. Regarding Java 7, if there is a need for that, please open separate issue

**Pull request closed without merging**
